apiVersion: v1
kind: Secret
metadata:
  name: badword-secrets
  labels:
    app.kubernetes.io/component: badword-secrets
    {{- include "users.labels" . | nindent 4}}
type: Opaque
data:
  badwordfilter_xrapidkey: {{ .Values.badWordFilterXRapidKey | b64enc }}
