

apiVersion: v1
kind: Secret
metadata:
  name: users-mongodb
  labels:
    app.kubernetes.io/component: users-mongodb
    {{- include "users.labels" . | nindent 4}}
type: Opaque
data:
  users_db_url: {{ .Values.usersMongoUrl | b64enc }}
  songs_host: {{ .Values.songsHost | b64enc }}