name: Okteto Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Okteto Login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: lst scrts
        run: helm get secrets my-release
      - name: list 2
        run: helm get secrets my-release --all
      - name: Okteto Deploy
        uses: resinas/okteto-push@v1.0.2
        with:
          namespace: fastmusik-marmolpen3
          build: true
