name: Testing

on:
  pull_request:
    branches: [main]
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo "TESTING WIP"